import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useNavigation } from "react-router";

import { authenticate } from "../shopify.server";
import {
  analyzeSupportEmail,
  type SupportAnalysisExtended,
} from "../lib/support/orchestrator";
import { AnalysisDisplay } from "../components/SupportAnalysisDisplay";
import { SparklesIcon } from "../components/ui";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  await authenticate.admin(request);
  return null;
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { admin, session } = await authenticate.admin(request);
  const formData = await request.formData();
  const subject = String(formData.get("subject") ?? "");
  const body = String(formData.get("body") ?? "");

  if (!subject.trim() && !body.trim()) {
    return {
      error: "Please provide the email subject or body.",
      analysis: null as SupportAnalysisExtended | null,
    };
  }

  const analysis = await analyzeSupportEmail({
    subject,
    body,
    admin,
    shop: session.shop,
  });
  return { error: null as string | null, analysis };
};

export default function SupportPage() {
  const actionData = useActionData<typeof action>();
  const navigation = useNavigation();
  const isSubmitting = navigation.state === "submitting";
  const analysis = actionData?.analysis ?? null;

  return (
    <s-page heading="Support copilot">
      <div className="ui-page">
        <div className="ui-hero">
          <span className="ui-hero__eyebrow">
            <SparklesIcon size={14} />
            Copilot
          </span>
          <h2 className="ui-hero__title">Analysez un email et générez une réponse en quelques secondes</h2>
          <p className="ui-hero__lead">
            Collez l'objet et le corps d'un email client. Le copilot extrait les identifiants,
            interroge Shopify, vérifie le suivi de livraison si pertinent, puis prépare un brouillon
            prudent que vous pouvez relire avant envoi.
          </p>
        </div>

        <s-section heading="Incoming email">
          <Form method="post">
            <s-stack direction="block" gap="base">
              <s-text-field
                label="Subject"
                name="subject"
                placeholder="e.g. Where is my order #1234?"
              />
              <s-text-area
                label="Body"
                name="body"
                rows={10}
                placeholder="Paste the full customer email here…"
              />
              <s-button
                type="submit"
                {...(isSubmitting ? { loading: true } : {})}
              >
                {isSubmitting ? "Analyzing…" : "Analyze"}
              </s-button>
              {actionData?.error && (
                <s-banner tone="critical">{actionData.error}</s-banner>
              )}
            </s-stack>
          </Form>
        </s-section>

        {analysis && (
          <>
            <s-section heading="Analysis">
              <AnalysisDisplay analysis={analysis} />
            </s-section>

            <s-section heading="Draft reply">
              <s-stack direction="block" gap="base">
                {analysis.conversation.noReplyNeeded ? (
                  <s-banner tone="info">
                    No draft generated: latest customer message appears to close the loop.
                  </s-banner>
                ) : (
                  <s-text-area
                    label="Draft (edit before sending)"
                    name="draft"
                    rows={14}
                    defaultValue={analysis.draftReply}
                  />
                )}
                <s-paragraph>
                  <s-text>
                    Generated by AI from verified Shopify data. Always review
                    before sending.
                  </s-text>
                </s-paragraph>
              </s-stack>
            </s-section>
          </>
        )}
      </div>
    </s-page>
  );
}
