import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";

import { authenticate } from "../shopify.server";
import { getSettings, saveSettings } from "../lib/support/settings";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const settings = await getSettings(session.shop);
  return { settings };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const formData = await request.formData();

  const saved = await saveSettings(session.shop, {
    signatureName: String(formData.get("signatureName") ?? ""),
    brandName: String(formData.get("brandName") ?? ""),
    tone: String(formData.get("tone") ?? "friendly"),
    language: String(formData.get("language") ?? "auto"),
    closingPhrase: String(formData.get("closingPhrase") ?? ""),
    shareTrackingNumber: formData.get("shareTrackingNumber") === "true",
    customerGreetingStyle: String(formData.get("customerGreetingStyle") ?? "auto"),
  });

  return { settings: saved, saved: true };
};

export default function SettingsPage() {
  const { settings: initial } = useLoaderData<typeof loader>();
  const actionData = useActionData<typeof action>();
  const navigation = useNavigation();
  const isSubmitting = navigation.state === "submitting";

  const settings = actionData?.settings ?? initial;

  return (
    <s-page heading="Reply settings">
      <s-section heading="Draft personalization">
        <s-paragraph>
          These settings are applied to every draft reply generated by the
          support copilot.
        </s-paragraph>

        <Form method="post">
          <s-stack direction="block" gap="base">
            <s-text-field
              label="Signature name"
              name="signatureName"
              defaultValue={settings.signatureName}
              placeholder="e.g. Nathalie - Service Client"
              details="Displayed at the bottom of every draft."
            />

            <s-text-field
              label="Brand name"
              name="brandName"
              defaultValue={settings.brandName}
              placeholder="e.g. AMBIENT HOME"
              details="Shown under the signature name."
            />

            <s-select
              label="Tone"
              name="tone"
              value={settings.tone}
              details="How formal the draft should sound."
            >
              <s-option value="friendly">Friendly</s-option>
              <s-option value="formal">Formal</s-option>
              <s-option value="neutral">Neutral</s-option>
            </s-select>

            <s-select
              label="Reply language"
              name="language"
              value={settings.language}
              details="Auto = match the customer's language. The entire reply (including closing) will use a single language."
            >
              <s-option value="auto">Auto (match customer)</s-option>
              <s-option value="fr">French</s-option>
              <s-option value="en">English</s-option>
            </s-select>

            <s-text-field
              label="Custom closing phrase"
              name="closingPhrase"
              defaultValue={settings.closingPhrase}
              placeholder="e.g. Cordialement,"
              details="Leave blank to use the default for the selected tone. Will be translated if it doesn't match the reply language."
            />

            <s-select
              label="How to address the customer"
              name="customerGreetingStyle"
              value={settings.customerGreetingStyle}
              details="The AI will always use its judgment to avoid using a company name as a person's name, or assuming gender."
            >
              <s-option value="auto">Auto — AI decides (recommended)</s-option>
              <s-option value="first_name">First name only (e.g. "Bonjour Karine,")</s-option>
              <s-option value="full_name">Full name (e.g. "Bonjour Karine Ruby,")</s-option>
              <s-option value="neutral">Neutral — never use the name</s-option>
            </s-select>

            <s-select
              label="Include tracking number in draft"
              name="shareTrackingNumber"
              value={settings.shareTrackingNumber ? "true" : "false"}
              details="Set to No if you use a dropshipper and don't want tracking details shared with customers."
            >
              <s-option value="true">Yes — include tracking number and link</s-option>
              <s-option value="false">No — hide tracking info (dropshipping)</s-option>
            </s-select>

            <s-button
              type="submit"
              {...(isSubmitting ? { loading: true } : {})}
            >
              Save settings
            </s-button>

            {actionData?.saved && (
              <s-banner tone="success">Settings saved.</s-banner>
            )}
          </s-stack>
        </Form>
      </s-section>
    </s-page>
  );
}
